import { FC } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import {
  FeaturesHeroCardContent,
  HomeFeatureContent,
  AdditionalFeatureContent,
} from '../helpers/content';

import HomeCard from '../components/cards/HomeCard';
import FeatureCard from '../components/cards/FeatureCard';
import BetaCard from '../components/cards/BetaCard';

const features: NextPage = () => {
  const { photo, title, info } = FeaturesHeroCardContent;

  return (
    <section>
      <Head>
        <title>Features | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCard
        photo={photo}
        title={title}
        info={info}
        accent={true}
        button={false}
        color="white"
        name={title}
        photoPosition="right"
      />
      {HomeFeatureContent.map(({ title, info, image }) => (
        <FeatureCard title={title} info={info} image={image} key={title} />
      ))}
      {AdditionalFeatureContent.map(({ title, info, image }) => (
        <FeatureCard title={title} info={info} image={image} key={title} />
      ))}
      <BetaCard />
    </section>
  );
};

export default features;
