import { useEffect } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';

import useStore from '../helpers/store';

import classes from '../styles/pages/features.module.css';

import { FeaturesHeroCardContent, AllFeatureContent } from '../helpers/content';

import HomeCard from '../components/cards/HomeCard';
import FeatureCard from '../components/cards/FeatureCard';
import BetaCard from '../components/cards/BetaCard';

const features: NextPage = () => {
  const { photoS, photoM, photoL, title, info } = FeaturesHeroCardContent;
  const { setScreenWidth } = useStore();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const width = window.innerWidth;
      setScreenWidth(width);
    }
  }, []);

  return (
    <section className={classes.container}>
      <Head>
        <title>Features | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCard
        photoS={photoS}
        photoM={photoM}
        photoL={photoL}
        title={title}
        info={info}
        accent={true}
        button={false}
        color="white"
        name={title}
        photoPosition="right"
      />
      <div className={classes['feature-container']}>
        {AllFeatureContent.map((content) => (
          <FeatureCard {...content} key={content.title} />
        ))}
      </div>

      <BetaCard />
    </section>
  );
};

export default features;
