import type { NextPage } from 'next';
import Head from 'next/head';
import HomeCard from '../components/cards/HomeCard';

import classes from '../styles/Home.module.css';
import createAndShare from '../public/assets/home/mobile/create-and-share.jpg';
import beautifulStories from '../public/assets/home/mobile/beautiful-stories.jpg';
import designedforEveryone from '../public/assets/home/mobile/designed-for-everyone.jpg';

const Home: NextPage = () => {
  return (
    <section className={classes.container}>
      <Head>
        <title>Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCard
        photo={createAndShare}
        accent={true}
        color="white"
        title="create and share you photo stories."
        info="Photosnap is a platform for photographers and visual storytellers. We
          make it easy to share photos, tell stories and connect with others."
      />
      <HomeCard
        photo={beautifulStories}
        accent={false}
        color="black"
        title="beautiful stories every time"
        info="We provide design templates to ensure your stories look terrific. Easily add photos, text, embed maps and media from other networks. Then share your story with everyone."
      />
      <HomeCard
        photo={designedforEveryone}
        accent={false}
        color="black"
        title="designed for everyone"
        info="Photosnap can help you create stories that resonate with your audience.  Our tool is designed for photographers of all levels, brands, businesses you name it."
      />
    </section>
  );
};

export default Home;
