import { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import useStore from '../helpers/store';

import HomeCard from '../components/cards/HomeCard';
import PhotoCard from '../components/cards/PhotoCard';
import Features from '../components/ui/Features';

import {
  HomeCardContent,
  StoriesPhotoCardContent,
  FeatureContent,
} from '../helpers/content';

import classes from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { setScreenWidth } = useStore();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const width = window.innerWidth;
      setScreenWidth(width);
    }
  }, []);
  return (
    <section className={classes.container}>
      <Head>
        <title>Photosnap | Your Stories, Your Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {HomeCardContent.map((content) => (
        <HomeCard {...content} button={true} key={content.title} />
      ))}

      <div className={classes['story-container']}>
        {StoriesPhotoCardContent.slice(0, 4).map((content) => (
          <PhotoCard {...content} date="" key={content.title} />
        ))}
      </div>
      <Features content={FeatureContent.slice(0, 3)} />
    </section>
  );
};

export default Home;
