import type { NextPage } from 'next';
import Head from 'next/head';

import HomeCard from '../components/cards/HomeCard';
import PhotoCard from '../components/cards/PhotoCard';
import Features from '../components/ui/Features';

import {
  HomeCardContent,
  HomePhotoCardContent,
  HomeFeatureContent,
} from '../helpers/content';

import classes from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <section className={classes.container}>
      <Head>
        <title>Photosnap | Your Stories, Your Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {HomeCardContent.map(
        ({ name, title, photo, photoPosition, accent, color, info }) => (
          <HomeCard
            name={name}
            title={title}
            photo={photo}
            accent={accent}
            color={color}
            info={info}
            photoPosition={photoPosition}
            key={title}
          />
        )
      )}
      {HomePhotoCardContent.map(({ title, author, photoS }) => (
        <PhotoCard title={title} author={author} photo={photoS} key={title} />
      ))}
      <Features content={HomeFeatureContent} />
    </section>
  );
};

export default Home;
