import type { NextPage } from 'next';
import Head from 'next/head';

import { PricingHeroCardContent } from '../helpers/content';

import HomeCard from '../components/cards/HomeCard';
import Pricing from '../components/ui/Pricing';

const pricing: NextPage = () => {
  const { photo, title, info } = PricingHeroCardContent;
  return (
    <section>
      <Head>
        <title>Pricing | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCard
        photo={photo}
        title={title}
        info={info}
        accent={true}
        button={false}
        color="white"
        name={title}
        photoPosition="right"
      />
      <Pricing />
    </section>
  );
};

export default pricing;
