import { useEffect } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';

import useStore from '../helpers/store';

import { PricingHeroCardContent } from '../helpers/content';

import HomeCard from '../components/cards/HomeCard';
import Prices from '../components/ui/Prices';
import Included from '../components/ui/Included';
import BetaCard from '../components/cards/BetaCard';

const Pricing: NextPage = () => {
  const { ...content } = PricingHeroCardContent;
  const { setScreenWidth } = useStore();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const width = window.innerWidth;
      setScreenWidth(width);
    }
  }, [setScreenWidth]);

  return (
    <section>
      <Head>
        <title>Pricing | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCard
        {...content}
        accent={true}
        button={false}
        color="white"
        name={content.title}
        photoPosition="right"
      />
      <Prices />
      <Included />
      <BetaCard />
    </section>
  );
};

export default Pricing;
