import { FC, useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image, { StaticImageData } from 'next/image';

import useStore from '../helpers/store';

import classes from '../styles/pages/stories.module.css';

import PhotoCard from '../components/cards/PhotoCard';
import ArrowBtn from '../components/buttons/ArrowBtn';

import {
  StoriesPhotoCardContent,
  StoriesHeroCardContent,
} from '../helpers/content';

const stories: NextPage = () => {
  const { setScreenWidth } = useStore();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const width = window.innerWidth;
      setScreenWidth(width);
    }
  }, []);
  return (
    <section className={classes.container}>
      <Head>
        <title>Stores | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedStory />
      <div className={classes['card-container']}>
        {StoriesPhotoCardContent.map((content) => (
          <PhotoCard {...content} key={content.title} />
        ))}
      </div>
    </section>
  );
};

// Main Hero Section on "Stories" page
const FeaturedStory: FC = () => {
  const { headline, title, date, author, info, photoS, photoM, photoL } =
    StoriesHeroCardContent;
  const [picture, setPicture] = useState<StaticImageData>(photoS);

  const { screenWidth } = useStore();

  useEffect(() => {
    console.log(screenWidth);
    if (screenWidth >= 1280) {
      setPicture(photoL);
    } else if (screenWidth >= 768 && screenWidth < 1280) {
      setPicture(photoM);
    } else {
      setPicture(photoS);
    }
  }, [screenWidth]);
  return (
    <div className={classes['hero-container']}>
      <div className={classes['photo-container']}>
        <Image
          layout="responsive"
          objectFit="contain"
          src={picture}
          alt={title}
        />
      </div>
      <div className={classes['content-container']}>
        <p className={classes.headline}>{headline}</p>
        <h2 className={classes.title}>{title}</h2>
        <div className={classes['sub-info-container']}>
          <p className={classes.date}>{date}</p>
          <p className={classes.author}>{author}</p>
        </div>
        <p className={classes.info}>{info}</p>
        <ArrowBtn title="read the story" color="white" />
      </div>
    </div>
  );
};

export default stories;
