import { FC } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import classes from '../styles/pages/stories.module.css';
import photo from '../public/assets/stories/mobile/moon-of-appalacia.jpg';
import ArrowBtn from '../components/buttons/ArrowBtn';

import { StoriesPhotoCardContent } from '../helpers/cards/PhotoCardContent';
import PhotoCard from '../components/cards/PhotoCard';

const stories = () => {
  return (
    <section className={classes.container}>
      <Head>
        <title>Stores | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedStory />
      {StoriesPhotoCardContent.map(({ author, title, photoS, date }) => (
        <PhotoCard author={author} title={title} photo={photoS} date={date} />
      ))}
    </section>
  );
};

const FeaturedStory: FC = () => {
  return (
    <div className={classes['hero-container']}>
      <Image
        layout="responsive"
        objectFit="contain"
        src={photo}
        alt="Moon of Appalacia"
      />
      <div className={classes['content-container']}>
        <p className={classes.headline}>last month's featured story</p>
        <h2 className={classes.title}>hazy full moon of appalachia</h2>
        <div className={classes['sub-info-container']}>
          <p className={classes.date}>March 2nd 2020</p>
          <p className={classes.author}>by John Appleseed</p>
        </div>
        <p className={classes.info}>
          The dissected plateau area, while not actually made up of geological
          mountains, is popularly called "mountains," especially in eastern
          Kentucky and West Virginia, and while the ridges are not high, the
          terrain is extremely rugged.
        </p>
        <ArrowBtn title="read the story" color="white" />
      </div>
    </div>
  );
};

export default stories;
