import { FC } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import classes from '../styles/pages/stories.module.css';

import PhotoCard from '../components/cards/PhotoCard';
import ArrowBtn from '../components/buttons/ArrowBtn';

import {
  StoriesPhotoCardContent,
  StoriesHeroCardContent,
} from '../helpers/content';

const stories = () => {
  return (
    <section className={classes.container}>
      <Head>
        <title>Stores | Photosnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedStory />
      {StoriesPhotoCardContent.map(({ author, title, photoS, date }) => (
        <PhotoCard author={author} title={title} photo={photoS} date={date} />
      ))}
    </section>
  );
};

// Main Hero Section on "Stories" page
const FeaturedStory: FC = () => {
  const { headline, title, date, author, info, photoS } =
    StoriesHeroCardContent;
  return (
    <div className={classes['hero-container']}>
      <Image layout="responsive" objectFit="contain" src={photoS} alt={title} />
      <div className={classes['content-container']}>
        <p className={classes.headline}>{headline}</p>
        <h2 className={classes.title}>{title}</h2>
        <div className={classes['sub-info-container']}>
          <p className={classes.date}>{date}</p>
          <p className={classes.author}>{author}</p>
        </div>
        <p className={classes.info}>{info}</p>
        <ArrowBtn title="read the story" color="white" />
      </div>
    </div>
  );
};

export default stories;
